export { HomeBanner } from './HomeBanner'
export { HomePOSList } from './HomePOSList'
export { HelpingSection } from './HelpingSection'
export { HelpingPOSSection } from './HelpingPOSSection'
export { MerchantFeeSection } from './MerchantFeeSection'
export { CompetitiveAdvantageSection } from './CompetitiveAdvantageSection'
export { CompetitiveRatesSection } from './CompetitiveRatesSection'
export { TestimonialsSection } from './TestimonialsSection'
